### ISSUE TITLE
安装Catalina 10.15.3后USB3.0接口无法识别USB3.0及以上的U盘（USB2.0接口可以），同时触控板仅仅可以操作鼠标箭头移动但无法使用点击功能

### ISSUE THREAD

**Issue by Spnail66** [XStar-Dev/HP_OMEN-2Pro_Hackintosh#1]
目前，本人的电脑配置和您上面提供的HP暗影精灵2 pro配置基本一致，仅仅处理器为i7及内存和硬盘后期更换存在差异，同时BOIS更新到了F53，在安装使用过程中存在如下的问题：
1. 电脑USB接口问题
[USB3.0接口无法使用，可以使用无线鼠标（带接收器的）和读取2.0接口的U盘，但是USB3.0及以上的U盘无法读取。USB2.0接口可以正常使用。
*注：Hackintool v2.8.0软件打开“USB控制器”页面显示USB接口有三个，均为USB3.0接口，且分别是0*03、0*04和0*07接口，分别对应USB Receiver、HP Wide Vision HD和IOUSBHostDevice三个，同时连接速度分别为12Mbps、480Mbps和12Mbps，而非5Gbs最大值。
2.触摸板无法使用
触控板可以移动鼠标（屏幕上），但是无法实现鼠标的点击事件，仅仅可以通过左右按压的方式点击选择，可以有时候也会失效。
除了上述的问题，其他基本上没有吹安明显的问题，EFI特别好，谢谢啦！

**Comment by XStar-Dev** [comment]
1、你使用的是CLOVER引导还是OpenCore引导
2、关于USB的定制在USBPorts里面，你可以看看应该没有问题。你说的显示的USB接口三个都是USB3.0应该不对，这种应该是USB定制没加载导致的。如果加载了，你能清楚地看到04和07是内置端口（Internal），而03为USB2.0，只有SS01和SS02是USB3.0. USB3.0的问题偶尔插上可能识别到重新插拔一般能解决。目前来看，你应该是USB定制文件USBPorts.kext没加载导致的，你是不是改过SMBIOS？
3、触摸板问题：我测试除了偶尔会抽风，大部分时间还是比较正常的，最多三指手势
4、建议使用我最新上传的OpenCore引导进行使用，我个人使用没什么问题

**Comment by XStar-Dev** [comment]
1、你使用的是CLOVER引导还是OpenCore引导？
2、关于USB的定制在USBPorts里面，你可以看看应该没有问题。你说的显示的USB接口三个都是USB3.0应该不对，这种应该是USB定制没加载导致的。如果加载了，你能清楚地看到04和07是内置端口（Internal），而03为USB2.0，只有SS01和SS02是USB3.0. USB3.0的问题偶尔插上可能识别到重新插拔一般能解决。目前来看，你应该是USB定制文件USBPorts.kext没加载导致的，你是不是改过SMBIOS？
3、触摸板问题：我测试除了偶尔会抽风，大部分时间还是比较正常的，最多三指手势
4、建议使用我最新上传的OpenCore引导进行使用，我个人使用没什么问题

**Comment by XStar-Dev** [comment]
还有，如果要达到5.0 Gbps，你需要用3.0的设备才可以，比如3.0的U盘，这是常识。内置摄像头走的是2.0，480MBps也是正确的

**Comment by Spnail66** [comment]
好的，我再查看一下，如果有什么问题再和您讨论，谢谢啦！

2020-02-04 16:51 GMT+08:00, iStarForever <notifications@github.com>:

**Comment by Spnail66** [comment]
已经解决了，谢谢啦！

**Comment by ZyoHuang** [comment]
我在m.2 SATA协议移动硬盘上顺利安装了Catalina 10.15.3，但是在USB3.0插口上用经常出现卡死状况，还有开机成功后登陆然后就卡死了，但是USB2.0没有这个问题，会是个什么问题呢？
