### ISSUE TITLE
clover启动Windows10蓝屏

### ISSUE THREAD

**Issue by deyuf** [XStar-Dev/HP_OMEN-2Pro_Hackintosh#10]
不知道什么原因，用Clover启动Windows 10反而会蓝屏，启动时加载条转半圈就会停止，然后进入蓝屏界面。Windows是测试版的20H2。用Windows自己的引导。Windows就能正常启动。

**Comment by XStar-Dev** [comment]
CLOVER那个引导我已经没有更新过了，但是一般来说CLOVER引导win10不至于蓝屏的。建议尝试下OpenCore吧。
