### ISSUE TITLE
惠普暗影精灵3普通版本外接显示器有解决方案吗

### ISSUE THREAD

**Issue by jzsn2018** [XStar-Dev/HP_OMEN-2Pro_Hackintosh#12]
最近好不容易装上了黑苹果，但是想扩展屏幕，试了惠普暗影精灵3普通版本笔记本的minDP转HDMI和笔记本自带的HDMI接口都没有用？想知道老哥你有扩展屏幕的思路吗？或者你已经实现了屏幕扩展的方法？谢谢🙏

**Comment by XStar-Dev** [comment]
暗影3的miniDP和HDMI都挂在独显上，因独显无法驱动故无法外接显示器，但是可以通过TypeC转HDMI来实现扩展，具体参考：https://github.com/shimakazechan/OMEN-by-HP-3-Hackintosh

**Comment by jzsn2018** [comment]
> 暗影3的miniDP和HDMI都挂在独显上，因独显无法驱动故无法外接显示器，但是可以通过TypeC转HDMI来实现扩展，具体参考：https://github.com/shimakazechan/OMEN-by-HP-3-Hackintosh

谢谢老哥,早一点看到就好了,我就不用买那么多转接线不,过还好,我已经成功了
