### ISSUE TITLE
WIFI联网问题基本解决

### ISSUE THREAD

**Issue by yfxiongda** [XStar-Dev/HP_OMEN-2Pro_Hackintosh#3]
远景论坛上面有大神弄出来了

👉[【突破！！intel wifi成功联网！！！】intel wifi 7265ac已实现大部分功能](http://bbs.pcbeta.com/viewthread-1838489-1-1.html)
经本人测试，一次成功

安装方法：

* 下载文件到桌面，并解压

* 修改里面的 `Info.plist` 文件，把WIFI名称和密码改成自己的

* 运行

  ```bash
  sudo chown -R root:wheel ./AppleIntelWiFi.kext
  ```

  ```bash
  sudo kextload ./AppleIntelWiFi.kext
  ```

* 如果不行尝试刷新缓存

存在的问题

* 网速较慢，有丢包（要啥自行车啊）
* 不能实时输入密码，需要自己改文件

**Comment by XStar-Dev** [comment]
Intel WiFi的路还很长，这个无法正常使用，存在的问题如下：
1. 网速慢，丢包十分严重，网页交互数据量较大时甚至存在内核崩溃导致重启
2. 因为这个驱动wifi验证部分没有走IO80211Family，所以SSID和密码写死了，想知道详细去了解下iwm和IOKit
3. 不支持IPv6
4. 不支持802.11ac连接，频段被限制
想日用还是老实换94352Z或者其他可用的免驱卡
还有，别随意开issue，issue是用来反馈问题的
