### ISSUE TITLE
请问更换网卡的话是不是dw1560最合适？

### ISSUE THREAD

**Issue by MrGuin** [XStar-Dev/HP_OMEN-2Pro_Hackintosh#4]
1820跟苹果原装网卡都不推荐吗？

**Comment by XStar-Dev** [comment]
我来给你总结一下我所知道的情况吧，博通网卡基本是放三个驱动就能用，免驱卡不要放。

BCM94350ZAE（DW1820A）已知10.15下不需要屏蔽，禁用ASPM，热启动完全正常。冷启动测试如下：

1. 不加载网卡驱动，brcmfx-driver=0，成功启动，蓝牙正常使用
2. 加载网卡驱动，和蓝牙一起驱动，最后跑完代码大概率卡在进度条处，有可能能进系统但是会很卡，事实上，这个时候蓝牙也不正常。

BCM94352Z（DW1560）无需屏蔽，测试全部正常

苹果原装卡，我没有，其他人测试可行，但是2Pro主板网卡处有电容挡住，无法直接安装，曾经有人通过飞线解决，不推荐。

目前黑苹果网卡价格均被恶意炒高，不是特别刚需，不推荐入手，像DW1560价格已经达到300，远超成本价，所以自己斟酌买还是不买，最后记住，DW1820A在暗影系列上都有兼容性问题，目前的结论是加载macOS驱动前必须有过一次完整的上电过程下次启动才可正常（即热启动）。

**Comment by MrGuin** [comment]
多谢🙏，我这环境必须用Wi-Fi和蓝牙，DW1560淘宝全新都320起步，最后闲鱼240入了联想拆下来的，等到了换上试试
