### ISSUE TITLE
更新10.15.4以后，使用本OpenCore引导包出现一些问题

### ISSUE THREAD

**Issue by Spnail66** [XStar-Dev/HP_OMEN-2Pro_Hackintosh#5]
在更新了最新的10.15.4版本以后，配合您上面提供的OpenCore引导文件可以正常的进入系统桌面，但仍然存在如下的问题：
①电脑外放无法使用，即电脑在播放音乐等操作时不发出声音（疑似声卡驱动版本需要更新），自我检查声卡硬件没有任何问题；
②电脑在关机的时候桌面的“程序坞”会仍然存在，无法退出直至关机；
③Windows和Mac OS的时间不同步，差近8个小时，在打开Mac OS进行网络时间更新以后，重启后登陆Windows系统时间会相差8个小时，在之前的版本中未出现此类问题。
上面是我在使用过程中出现的问题，可能一些小细节上的问题没有发现，望有解决方案的话给予共享，谢谢啦！

**Comment by XStar-Dev** [comment]
OpenCore 我现在默认使用的是VoodooHDA，不会自动切换，使用外放请手动切换输出设备（状态栏或者偏好设置都可以切换，并且热启动很容易造成外放无声（特别是当你插着耳机win热启动到Mac基本会造成外放无声），冷启动基本无问题，VoodooHDA外放声音小，这个比较蛋疼，想用AppleALC请修改config Kernel-Add里面取消勾选VoodooHDA，勾选AppleALC，外放声音应该能稍微大点，但是肯定没win声音大，原因很简单，win下的声音完全是靠B&O音效软件增益的，但是mac没有，当你更改win下声卡驱动为标准HDA驱动时，声音和mac是一样的）。
关机程序坞问题没发现或者因为没什么影响所以没注意。
时间问题，你之前没出现只不过纯属巧合，想让双系统时间同步，请修改win注册表，使用UTC时间，方法如下，打开命令行输入下列语句，重启到mac重新联网同步时间，再度进入win即可正常
Reg add HKLM\SYSTEM\CurrentControlSet\Control\TimeZoneInformation /v RealTimeIsUniversal /t REG_DWORD /d 1

**Comment by Spnail66** [comment]
好的，那我先试试，谢谢啦！

**Comment by XStar-Dev** [comment]
关机卡Dock栏问题已确认是系统问题，与EFI无关。

**Comment by Spnail66** [comment]
OK，非常感谢！
