### ISSUE TITLE
使用后进不去系统

### ISSUE THREAD

**Issue by 2605759123** [XStar-Dev/HP_OMEN-2Pro_Hackintosh#6]
使用后进不去系统，卡死在这个页面，是什么情况呢？感谢
![微信图片_20200401063611](https://user-images.githubusercontent.com/43004851/78106722-8c523b00-7426-11ea-968b-5fedc19307d7.jpg)

**Comment by XStar-Dev** [comment]
AE_ALREADY_EXISTS 是ACPI某个对象已存在的错误
2 tables failed 19 successful，非常明显的问题，你没有删掉之前用过的EFI而直接覆盖使用了，导致部分东西重复加载，正常来说全部加载成功的话也才19个表，自己好好检查下ACPI里面是不是多余了东西，你应该是用的clover

**Comment by 2605759123** [comment]
我在这方面是个小白。。我把我所有的流程跟您说一下吧。
1.我的电脑型号和你一样，配置基本上和你readme上给的一样，不同在于SSD（我是原装的128G ssd）和网卡
2.我按你的要求下载了最新版的bios
3.我在黑果小兵上下载了

> [macOS Catalina 10.15.4 19E266 正式版 with Clover 5107原版镜像[双EFI版][UEFI and MBR]](https://blog.daliansky.net/macOS-Catalina-10.15.4-19E266-Release-version-with-Clover-5107-original-image-Double-EFI-Version-UEFI-and-MBR.html)

4.我将原EFI/CLOVER目录下的文件全部删掉，替换成您的，但是重启后发现在clover中不显示mac系统，也就没办法安装，无奈只好再换回黑果小兵原版的，这时clover有了macOS，但是也没有办法进去，卡在了一个页面。

5.我观察了你给的EFI文件夹和黑果小兵上面的，自认为你的是精简版的，因为目录结构不同，比如你的ACPI目录下直接就是.aml文件，而黑果小兵上面是\ACPI\patched下有.aml文件，您的\Drivers目录下是.efi，而黑果小兵上的\Drivers目录下是\BIOS，\off，\UEFI三个文件夹。

6.我使用你的\ACPI、\Drivers文件夹下的文件覆盖了黑果小兵对应文件夹下的同名文件；

7.删除了黑果小兵kexts\Other文件夹下的所有.kext,将你\Kexts下的.kext复制了进来。

8.此时如果替换config.plist，clover能找到macOS，但是安装失败了。

9.此时不替换config.plist，我成功安装了macOS，也成功进入了，但是系统很卡，也有很多问题。

10.安装后，我如果再使用你的config.plist替换原来的（此时仍然保留6-7的操作），也仍然进不去系统，报错就是我上面那张图。

11.安装后，我用你的文件替换EFI\CLOVER文件夹下的全部文件，clover中依然找不到macOS

**Comment by XStar-Dev** [comment]
要不你这样，黑果小兵的EFI里面只删除ACPI Kexts和config.plist，然后把我EFI里面的这三个部分复制进去
另外，安装失败的错误是什么，请描述一下

**Comment by 2605759123** [comment]
安全失败的错误我没有拍下来，我照你说的重新安装一下试试。
但是，你和黑果小兵的ACPI Kexts目录结构不同
黑果小兵的：\ACPI\patched\*.aml 你的：ACPI\*.aml
黑果小兵的：\kexts\Other\*.kext 你的：\Kexts\*.kext
我应该使用哪种目录结构？

**Comment by 2605759123** [comment]
当时我用你的\ACPI、\Drivers文件夹下的文件覆盖了黑果小兵对应文件夹下的同名文件(使用的是黑果小兵的目录结构)，并且删除了原来全部的Kexts替换成你的，也替换了config.plist，clover能找到macOS，但应该准确的说不是安装失败了，而是macOS的引导程序就没进去（也就是说没进去让选择磁盘安装的那个页面）

**Comment by XStar-Dev** [comment]
我 github 下面的是 OpenCore 引导哦，CLOVER在Release里面

**Comment by 2605759123** [comment]
哇，感谢，我可能选错了版本，我重新尝试一下，说实在，我并不知道这两个有什么区别，以为都差不多-_-

**Comment by 2605759123** [comment]
成功了！并且看起来没有什么问题，good!
