### ISSUE TITLE
你好，我想问一下能不能更新一下驱动

### ISSUE THREAD

**Issue by zhangzjjun** [XStar-Dev/HP_OMEN-2Pro_Hackintosh#7]
因为我看到上面的说的那个英特尔WIFI项目，今天好像更新了，解除了不少的bug，能不能编译一下kext，谢谢

**Comment by XStar-Dev** [comment]
答案是：不能。
想测试自己去编译（提示：更新是修复加密连接问题，SSID和密码写死，需要自己改）
