### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by su0weiqiang** [XStar-Dev/HP_OMEN-2Pro_Hackintosh#8]
大佬，我机器和你的一样，网卡也和你的一样，引导的时候出现三个选项：
1.EFI
2.Clean NVRAM
3. Reset NVRAM
我选择第一个之后，只出现Halting on critical error错误，无法继续下去，请问机器还要做什么设置吗？

**Comment by XStar-Dev** [comment]
你用什么软件添加引导项的，看起来是引导项加错了

**Comment by su0weiqiang** [comment]
我是单系统macos系统，直接删除原来EFI分区上CLOVER文件夹、将您的OC文件夹拷贝过去，然后重启的

**Comment by XStar-Dev** [comment]
进winpe，用EasyUEFI重新添加引导启动项，选择OC/OpenCore.efi

**Comment by su0weiqiang** [comment]
不行，添加了引导，进入oc选择启动系统之后还是原来的那三个选项，选择EFI之后，还是Halting on critical error这个错误。

**Comment by XStar-Dev** [comment]
那你选择选项 2 清除NVRAM，之后自动重启，看情况如何。如果还是一样，建议进入BIOS看看你的引导菜单里面有些什么

**Comment by su0weiqiang** [comment]
清除了，但是不会自动重启，需要手动重启。bios就是正常的U盘优先启动。如果搞不定就不用oc了，感谢哈~
