### ISSUE TITLE
关于启动项的问题的请教

### ISSUE THREAD

**Issue by su0weiqiang** [XStar-Dev/HP_OMEN-2Pro_Hackintosh#9]
你好，上个issue我的那个问题，我突然想到可能是oc引导没有读到我的mac系统盘的原因，我的是单硬盘单系统，系统盘名字为mac，你能将你oc引导选择系统的选项列一下给我看下吗？我的是：
1、EFI
2、Clean NVRAM
3、Reset NVRAM
不知道大神，你的引导菜单是怎么样的呀？

**Comment by XStar-Dev** [comment]
1. Windows
2. Macintosh HD
3. Macintosh HD (Recovery) 就是恢复模式
4和5就是clean和reset NVRAM

**Comment by su0weiqiang** [comment]
那就是oc引导没有读到我的mac系统盘的原因，启动错了，导致出现严重系统错误的提示。大神你知道要怎么解决吗？

**Comment by su0weiqiang** [comment]
找到问题了，是因为用时间机器恢复的，全新安装就可以了
